### ISSUE TITLE
How to build communote-server

### ISSUE THREAD

**Issue by hi-ko** [Communote/communote-server#1]
I followed http://communote.github.io/doc/dev_how_core.html but the doc seems to be somehow incomplete. I tried

    ~/communote-server/ mvn -f build/war-parent/pom.xml

but got complains for missing parent project ...

    Non-resolvable parent POM: Could not find artifact com.communote.server:communote-server-parent:pom:3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 13

What is the right sequence to build? Do you have a script or a full build archetype?

**Comment by rwi** [comment]
@hi-ko  you are right the documentation was incomplete. I just updated it with the required steps and you can give it another try. Please pull again before starting the build because I added some repositories to the POMs which are necessary for a successful build.
I hope it work's now.

**Comment by hi-ko** [comment]
@rwi thanks a lot for the prompt response. 
Now the build worked as described. You also may add 
- a hint to run mvn inside communote-server/communote
- a statement for required/tested versions of jdk and mvn.
I tested with jdk 1.8

Please don't forget to create releases to allow support ;-)
