### ISSUE TITLE
File download not working if filename contains spaces

### ISSUE THREAD

**Issue by cheindel** [Communote/communote-server#24]
There is a problem due to wrong enconding of file URLs in posts.

To reproduce the error, upload a file called sth. like "Communote 2.3.4.ipa" and try to download the file in Chromium.

The following link will be generated (but won't work):
https://MYSERVER/microblog/global/portal/files/62/Communote+2_3_4.ipa

If you change the link to %20 instead of +, it will work.
https://MYSERVER/microblog/global/portal/files/62/Communote%202_3_4.ipa

**Comment by rwi** [comment]
Yep the encoding is wrong but the link should actually still work, except you are using Communote behind an IIS. If that's the case you probably hit the [double encoding issue](https://blogs.iis.net/thomad/iis7-rejecting-urls-containing). As a workaround you could allow double escaping in IIS for Communote.

**Comment by cheindel** [comment]
We've implemented the double escaping setting in IIS for now. Do you have plans to improve this in a future release?
