### ISSUE TITLE
Changing rights of a topic with the REST API

### ISSUE THREAD

**Issue by lkdl** [Communote/communote-server#29]
Hello,

I have an issue regarding the REST API of Communote, especially concerning subresources.

Precisely, I am trying to change the rights of a topic using the REST API. As stated in the [documentation](https://communote.github.io/generated/rest-api/gen/resources/topic.html#Right_Resource), this should be possible by sending a PUT request to the `.../topics/ID/rights/ID` endpoint.

The first problem is, that I am not sure about the second `ID` parameter and what its value should be. Is the second `ID` parameter also
the topic id?

Assuming both of the `ID`s are the topic id, sending the following PUT request to the endpoint yields the following response:

Request:

```
PUT /microblog/global/api/rest/3.0/topics/4/rights/4?_method=PUT HTTP/1.1
Host: localhost:8081
Authorization: Basic [...]
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

allCanWrite=true&allCanRead=true
```

Response:

```
{
  "message": "Blogrechte erfolgreich bearbeitet.",
  "status": "OK"
}
```

Despite the successful response, checking the topics rights again (GET to `.../topics/ID/rights/ID`) shows that the topics rights did not change:

```
{
  "status": "OK",
  "result": {
    "allCanWrite": false,
    "allCanRead": false,
    "publicAccess": false,
    "managingUserIds": [
      1
    ],
    "readingUserIds": null,
    "writingUserIds": null
  }
}
```

Does this happen due to a misunterstanding of the role of the second `ID` parameter? Or am I missing something else here?

Thank you in advance!

**Comment by scrobbleme** [comment]
Hello @lkdl 

When I'm not wrong you should use PUT on topic, to edit the topic: https://communote.github.io/generated/rest-api/gen/resources/topic.html#PUT_-_Topic_Resource

The rights resource is only used to edit specifig user/group rights.

(@rwi Where is it possible to download the generated JAVA client lib?)

**Comment by lkdl** [comment]
Thanks for your fast reply!

The linked part of the documentation looks promising, but as it seems, I'm still out of luck. As described, I issued a PUT request to the topic resource with all mandatory parameters and the rights I want to change:

```
PUT /microblog/global/api/rest/3.0/topics/4 HTTP/1.1
Host: localhost:8081
Authorization: Basic [...]
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
allCanWrite=true&allCanRead=true&topicId=4
```

Communote responds with:

```
{
  "message": "Während der Parametervalidierung ist ein Fehler aufgetreten.",
  "status": "ERROR",
  "errors": [
    {
      "cause": "title",
      "message": "Das Feld darf nicht leer sein."
    }
  ]
}
```

Setting the field `title` in the body of the request (where it's mentioned in the docu, but not as mandatory) yields to the same response. However, setting the `title` as a parameter leads to the following:

Request:

```
PUT /microblog/global/api/rest/3.0/topics/4?title=test HTTP/1.1
Host: localhost:8081
Authorization: Basic [...]
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

allCanWrite=true&allCanRead=true&topicId=4
```

Response:

```
{
  "message": "Die Eigenschaften des Themas wurden erfolgreich gespeichert.",
  "status": "OK",
  "result": 4
}
```

Unfortunately, upon closer inspection of the topic, it seems that nothing have changed:

```
{
  "status": "OK",
  "result": {
    "topicId": "4",
    "children": [],
    "lastModificationDate": 1485250287235,
    "topicEmail": null,
    "createSystemNotes": false,
    "description": null,
    "tags": [],
    "alias": "test",
    "title": "test",
    "userRole": "MANAGER",
    "isFollow": false,
    "properties": null,
    "allCanWrite": false,
    "allCanRead": false,
    "externalObjects": null,
    "roleExternals": null,
    "roles": null,
    "profileImageId": "default",
    "profileImageVersion": "1476719226412_t2",
    "lastProfileImageModificationDate": 0,
    "bannerImageId": "default",
    "bannerImageVersion": "1476719226412_t2",
    "lastBannerImageModificationDate": 0,
    "crawlLastModificationDate": 1485250287235
  }
}
```

**Comment by rwi** [comment]
@lkdl it seems like the body of the request is ignored. This might be an issue with the PUT method. Could you give [tunneling](https://communote.github.io/generated/rest-api/gen/resources/usage.html#Tunneling) a try? So what you basically have to do is send a POST request to the URL /microblog/global/api/rest/3.0/topics/4?_method=PUT with the body set to

```
allCanWrite=true&allCanRead=true&title=test
```

Despite being marked as mandatory, the topicId attribute should not be part of the body because it is already provided in the resource URL. But you should set the alias, description, tags and properties attributes to the current values otherwise they would be updated with defaults which are no description, tags or properties and an alias which is derived from the title.
Because of this the rights subresource is the better choice when only editing the allCan-flags but unfortunately its [handler](https://github.com/Communote/communote-server/blob/v3.4.1/communote/plugins/rest-api/3.0/implementation/src/main/java/com/communote/plugins/api/rest/v30/resource/topic/right/RightResourceHandler.java) has a silly copy-paste bug which makes it unusable :worried:

**Comment by rwi** [comment]
@scrobbleme the REST API client can be found on [bintray](https://bintray.com/communote/maven/communote-core-plugins#files/com/communote/communote-rest-api-3.0-client)

**Comment by rwi** [comment]
@lkdl with [release 3.4.3](https://github.com/Communote/communote-server/releases/tag/v3.4.3) the `.../topics/ID/rights/ID` endpoint now works as expected because issue #30 has been fixed. Btw. the second ID is a pseudo ID which can be any number.
