### ISSUE TITLE
Settings for plugin development

### ISSUE THREAD

**Issue by datenwort** [Communote/communote-server#37]
Hi,

I try to get familar with creating plugins for our intranet based on communote. And I am stuck in configuring the plugins. Is there a list of possible items which can be used for

- parentViewId 
- visibleWidgets
- containerSelector

and so on.

**Comment by scrobbleme** [comment]
For a list of widgets you may open the developer tools of your browser and insert into the console

`communote.configuration.mainPageViewManagerConfig.widgets`

This will give you a brief overview of registered widgets and their configuration (i.e. containerSelecter)

![image](https://user-images.githubusercontent.com/504835/29121869-9fe671c8-7d10-11e7-8853-609dff1f3473.png)

and 

`communote.configuration.mainPageViewManagerConfig.views`

will give you an overview over registered view. Everything before an underscore is propably a parentViewId

![image](https://user-images.githubusercontent.com/504835/29122033-26e38e4a-7d11-11e7-8c7c-d837c7f2acd2.png)

But for the container you may use anyone available within the page, as it is propably only a CSS selector.

**Comment by datenwort** [comment]
Thank you for the information. This is a beginning. Maybe it would be helpful to add this information to the plugin section.
