### ISSUE TITLE
request.getRemoteUser() returns different results

### ISSUE THREAD

**Issue by datenwort** [Communote/communote-server#49]
I am facing a very weird issue.

```
@Component
@Provides
@Instantiate
@UrlMapping(value = "/*/plugin/profile/extension")
public class ExtensionController implements Controller {

public ModelAndView handleRequest(HttpServletRequest request, HttpServletResponse response) throws Exception {
}
}
```

The call ```request.getRemoteUser()``` sometimes returns the id of the user and sometimes the alias.
I cannot reproduce the environment, but it changes from time to time.

Any clue on this?

**Comment by rwi** [comment]
That's simple, we don't set the remote user explicitly :wink:

To get the currently authenticated user please use the [SecurityHelper](https://github.com/Communote/communote-server/blob/master/communote/persistence/src/main/java/com/communote/server/core/security/SecurityHelper.java). Especially the `getCurrentUserId()` method is a good starting point. It gives you the ID of the currently logged in user, which in your case is the one who did the request to your controller, or null if no one is logged in.
The ID can be used to get further information about the user from the [UserManagement](https://github.com/Communote/communote-server/blob/master/communote/persistence/src/main/java/com/communote/server/core/user/UserManagement.java) by invoking `UserManagement.getUserById(Long userId, Converter<User, T> converter)`. The UserManagement is accessible via the [ServiceLocator](https://github.com/Communote/communote-server/blob/master/communote/api/src/main/java/com/communote/server/api/ServiceLocator.java)'s findService method.

**Comment by datenwort** [comment]
Thanks.
