### ISSUE TITLE
Link to documentation in contact page of installer leads to 404

### ISSUE THREAD

**Issue by rwi** [Communote/communote-server#5]
Link to documentation in microblog/global/installer/contact.do points to http://communote.github.io/doc which is responded with a 404.

**Comment by rwi** [comment]
@Psyphant can this be fixed in the documentation or should we change the link to http://communote.github.io/doc/home.html?

**Comment by Psyphant** [comment]
@rwi I just fixed the documentation and add a redirect from **/doc** to the **home.md**, because there is no **index.html** file inside the **doc** folder.
