### ISSUE TITLE
Enhance attachment upload

### ISSUE THREAD

**Issue by rwi** [Communote/communote-server#53]
When adding attachments to a note you currently only have the possibility to select a single file in the file chooser. If you want to add more files from the same directory you have to open the file dialogue again to select the next file.

This should be improved to allow:
- selecting multiple files in the file chooser
- Drag and Drop of files
- pasting image data from clipboard into the editor. The pasted image data should then be attached as an image file to the note.

The implementation should follow the progressive enhancement philosophy (only browsers supporting the feature will be enriched).

**Comment by scrobbleme** [comment]
@rwi Für Zwischenablage haben wir schon ein Plugin. Das sollte funktionieren und müsste sicher lediglich aktualisiert werden. (Funktioniert für Bilder und Text)
